version: 2.1

orbs: 
  win: circleci/windows@5
  matlab: mathworks/matlab@1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
  macos:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.medium.gen1
  windows: 
    win/default

jobs:
  build:
    parameters:
      os:
        type: executor
      release:
        type: string
    executor: <<parameters.os>>
    environment:
       MATLAB_LOG_DIR: /home/circleci/project/logs
       MW_DIAGNOSTIC_DEST: file
       MW_DIAGNOSTIC_SPEC: cppmicroservices::framework.*=all;install.*=all;
       MW_VERBOSE_HTTPCLIENT_CORE: 1
       MW_BATCH_LICENSING_ONLINE: true # testing online validation, can remove when this becomes the default
    steps:
      - checkout
      # Use AWS-based Ubuntu mirror for better connectivity.
      # See https://support.circleci.com/hc/en-us/articles/37474192881179-Resolving-Unable-to-connect-to-archive-ubuntu-com-403-Forbidden-Error-in-CircleCI
      - when:
          condition:
            equal: ["<<parameters.os>>", "linux"]
          steps:
            - run:
                name: Switch to AWS mirror
                command: |
                  sudo sed -i 's|http://archive.ubuntu.com|http://us-east-1.ec2.archive.ubuntu.com|g' /etc/apt/sources.list
                  sudo sed -i 's|http://security.ubuntu.com|http://us-east-1.ec2.archive.ubuntu.com|g' /etc/apt/sources.list

      # Make APT more robust to network connectivity issues.
      - when:
          condition:
            equal: ["<<parameters.os>>", "linux"]
          steps:
            - run:
                name: Configure APT behavior
                command: |
                  echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
                  echo 'Acquire::http::Timeout "30";' | sudo tee /etc/apt/apt.conf.d/99timeout
                  echo 'Acquire::Retries "3";' | sudo tee /etc/apt/apt.conf.d/99retries
                  echo 'Acquire::http::Pipeline-Depth "0";' | sudo tee /etc/apt/apt.conf.d/99pipeline
      - matlab/install:
          release: <<parameters.release>>
          products: Optimization_Toolbox Curve_Fitting_Toolbox
      - matlab/run-tests:
          source-folder: code
      - run:
          command: tar -cvzf matlab-logs.tar /home/circleci/project/logs
          when: on_fail
          shell: bash
      - store_artifacts:
          path: matlab-logs.tar
          when: on_fail

workflows:
  all-builds:
    jobs:
      - build:
         matrix:
           parameters:
              os: [linux, macos, windows]
              release: [R2021a, R2021b, R2022a, R2022b, R2023a, R2023b, R2024a, R2024b, R2025a, latest]
